// src/screens/CalendarScreen.tsx
import { useMemo, useState } from 'react';
import { TopBar } from '../components/TopBar';
import { InstitutionFilter } from '../components/InstitutionFilter';
import { ScheduleCard } from '../components/ScheduleCard';
import { useApp } from '../store/AppStore';
import { INSTITUTION_COLOR } from '../types';
import { WEEKDAY_LABEL, addDays, endOfMonth, fromDateKey, humanDate, monthGrid, startOfMonth, toDateKey } from '../lib/date';
import { describeWeather, forecastFor } from '../lib/weather';

/** 월간 달력 (기획서 핵심요구 4). 기관 필터·날씨 아이콘이 셀에 함께 붙는다. */
export function CalendarScreen() {
  const { occurrencesBetween, weather, settings } = useApp();
  const [cursor, setCursor] = useState(() => startOfMonth(new Date()));
  const [selected, setSelected] = useState(() => toDateKey(new Date()));

  const grid = useMemo(() => monthGrid(cursor), [cursor]);
  const monthOccurrences = useMemo(
    () => occurrencesBetween(fromDateKey(grid[0][0]), addDays(fromDateKey(grid[5][6]), 1)),
    [occurrencesBetween, grid],
  );

  const byDate = useMemo(() => {
    const map = new Map<string, typeof monthOccurrences>();
    for (const o of monthOccurrences) {
      const list = map.get(o.date) ?? [];
      list.push(o);
      map.set(o.date, list);
    }
    return map;
  }, [monthOccurrences]);

  const today = toDateKey(new Date());
  const selectedList = byDate.get(selected) ?? [];
  const monthLabel = `${cursor.getFullYear()}년 ${cursor.getMonth() + 1}월`;

  return (
    <>
      <TopBar
        title={monthLabel}
        subtitle={`${monthOccurrences.filter((o) => o.date.startsWith(toDateKey(cursor).slice(0, 7))).length}건`}
        actions={
          <div className="row">
            <button className="icon-btn" onClick={() => setCursor(startOfMonth(addDays(startOfMonth(cursor), -1)))} aria-label="이전 달">
              ‹
            </button>
            <button className="icon-btn" onClick={() => setCursor(startOfMonth(addDays(endOfMonth(cursor), 1)))} aria-label="다음 달">
              ›
            </button>
          </div>
        }
      />
      <div className="screen">
        <InstitutionFilter />

        <div className="cal-head" style={{ marginTop: 12 }}>
          {WEEKDAY_LABEL.map((w) => (
            <span key={w}>{w}</span>
          ))}
        </div>
        <div className="cal-grid">
          {grid.flat().map((key) => {
            const date = fromDateKey(key);
            const outside = date.getMonth() !== cursor.getMonth();
            const list = byDate.get(key) ?? [];
            const forecast = forecastFor(weather, key);
            return (
              <button
                key={key}
                className={`cal-cell ${outside ? 'out' : ''} ${key === today ? 'today' : ''} ${key === selected ? 'sel' : ''}`}
                onClick={() => setSelected(key)}
              >
                <span className={`d ${date.getDay() === 0 ? 'sun' : date.getDay() === 6 ? 'sat' : ''}`}>{date.getDate()}</span>
                <span className="cal-dots">
                  {list.slice(0, 6).map((o) => (
                    <span key={o.key} className="cal-dot" style={{ background: INSTITUTION_COLOR[o.schedule.institution] }} />
                  ))}
                </span>
                {settings.weatherEnabled && forecast && <span className="wx">{describeWeather(forecast.code).icon}</span>}
              </button>
            );
          })}
        </div>

        <p className="section-title">
          {humanDate(selected)} <span className="muted small">{selectedList.length}건</span>
        </p>
        {selectedList.length === 0 ? (
          <p className="muted small" style={{ padding: '0 2px' }}>
            선택한 날짜에 일정이 없습니다.
          </p>
        ) : (
          selectedList.map((o) => <ScheduleCard key={o.key} occurrence={o} forecast={forecastFor(weather, o.date)} />)
        )}
      </div>
    </>
  );
}

// src/screens/CalendarScreen.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import TopBar from '../components/TopBar.vue';
import InstitutionFilter from '../components/InstitutionFilter.vue';
import ScheduleCard from '../components/ScheduleCard.vue';
import { useAppStore } from '../stores/app';
import { INSTITUTION_COLOR } from '../types';
import type { Occurrence } from '../types';
import { WEEKDAY_LABEL, addDays, endOfMonth, fromDateKey, humanDate, monthGrid, startOfMonth, toDateKey } from '../lib/date';
import { describeWeather, forecastFor } from '../lib/weather';

/** 월간 달력 (기획서 핵심요구 4). 기관 필터·날씨 아이콘이 셀에 함께 붙는다. */
const store = useAppStore();
const cursor = ref(startOfMonth(new Date()));
const selected = ref(toDateKey(new Date()));
const today = toDateKey(new Date());

const grid = computed(() => monthGrid(cursor.value));
const cells = computed(() => grid.value.flat());
const monthLabel = computed(() => `${cursor.value.getFullYear()}년 ${cursor.value.getMonth() + 1}월`);

const monthOccurrences = computed(() =>
  store.occurrencesBetween(fromDateKey(grid.value[0][0]), addDays(fromDateKey(grid.value[5][6]), 1)),
);

const byDate = computed(() => {
  const map = new Map<string, Occurrence[]>();
  for (const occurrence of monthOccurrences.value) {
    const list = map.get(occurrence.date) ?? [];
    list.push(occurrence);
    map.set(occurrence.date, list);
  }
  return map;
});

const monthCount = computed(() => {
  const prefix = toDateKey(cursor.value).slice(0, 7);
  return monthOccurrences.value.filter((o) => o.date.startsWith(prefix)).length;
});

const selectedList = computed(() => byDate.value.get(selected.value) ?? []);

const dayClass = (key: string) => {
  const day = fromDateKey(key).getDay();
  return day === 0 ? 'sun' : day === 6 ? 'sat' : '';
};
</script>

<template>
  <TopBar :title="monthLabel" :subtitle="`${monthCount}건`">
    <template #actions>
      <div class="row">
        <button class="icon-btn" aria-label="이전 달" @click="cursor = startOfMonth(addDays(startOfMonth(cursor), -1))">‹</button>
        <button class="icon-btn" aria-label="다음 달" @click="cursor = startOfMonth(addDays(endOfMonth(cursor), 1))">›</button>
      </div>
    </template>
  </TopBar>

  <div class="screen">
    <InstitutionFilter />

    <div class="cal-head" style="margin-top: 12px">
      <span v-for="label in WEEKDAY_LABEL" :key="label">{{ label }}</span>
    </div>
    <div class="cal-grid">
      <button
        v-for="key in cells"
        :key="key"
        class="cal-cell"
        :class="{
          out: fromDateKey(key).getMonth() !== cursor.getMonth(),
          today: key === today,
          sel: key === selected,
        }"
        @click="selected = key"
      >
        <span class="d" :class="dayClass(key)">{{ fromDateKey(key).getDate() }}</span>
        <span class="cal-dots">
          <span
            v-for="occurrence in (byDate.get(key) ?? []).slice(0, 6)"
            :key="occurrence.key"
            class="cal-dot"
            :style="{ background: INSTITUTION_COLOR[occurrence.schedule.institution] }"
          />
        </span>
        <span v-if="store.settings.weatherEnabled && forecastFor(store.weather, key)" class="wx">
          {{ describeWeather(forecastFor(store.weather, key)!.code).icon }}
        </span>
      </button>
    </div>

    <p class="section-title">
      {{ humanDate(selected) }} <span class="muted small">{{ selectedList.length }}건</span>
    </p>
    <p v-if="selectedList.length === 0" class="muted small" style="padding: 0 2px">선택한 날짜에 일정이 없습니다.</p>
    <ScheduleCard
      v-for="occurrence in selectedList"
      :key="occurrence.key"
      :occurrence="occurrence"
      :forecast="forecastFor(store.weather, occurrence.date)"
    />
  </div>
</template>
