// src/screens/SettingsScreen.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import TopBar from '../components/TopBar.vue';
import { useAppStore } from '../stores/app';
import { useMailAccount } from '../composables/useMailAccount';
import { INSTITUTION_LABEL } from '../types';
import type { InstitutionKind, Region } from '../types';
import { offsetLabel } from '../lib/date';
import { OFFSET_CHOICES, ensurePermission } from '../lib/notifications';
import { PRESET_REGIONS, searchRegion } from '../lib/weather';
import { getGoogleClientId, setGoogleClientId } from '../lib/mail/gmail';

const store = useAppStore();
const router = useRouter();
const mail = useMailAccount();
const institutions: InstitutionKind[] = ['kindergarten', 'daycare', 'home'];

const permission = ref(typeof Notification === 'undefined' ? 'denied' : Notification.permission);
const query = ref('');
const results = ref<Region[]>([]);
const searching = ref(false);
const searchError = ref('');
const clientId = ref(getGoogleClientId());
const clientIdSaved = ref(false);

function toggleOffset(offset: number): void {
  const current = store.settings.defaultOffsets;
  store.updateSettings({
    defaultOffsets: current.includes(offset) ? current.filter((o) => o !== offset) : [...current, offset],
  });
}

function pickRegion(region: Region): void {
  store.updateSettings({ region });
  results.value = [];
  query.value = '';
  void store.refreshWeather(true);
}

async function search(): Promise<void> {
  if (!query.value.trim()) return;
  searching.value = true;
  searchError.value = '';
  try {
    results.value = await searchRegion(query.value.trim());
  } catch {
    searchError.value = '지역을 검색하지 못했습니다. 오프라인이면 아래 목록에서 골라 주세요.';
  } finally {
    searching.value = false;
  }
}

function saveClientId(): void {
  setGoogleClientId(clientId.value);
  clientIdSaved.value = true;
  mail.refresh();
  window.setTimeout(() => (clientIdSaved.value = false), 2000);
}

function loadSample(): void {
  if (window.confirm('샘플 일정과 계획표 메일로 덮어쓸까요?')) store.loadSampleData();
}

function reset(): void {
  if (!window.confirm('저장된 모든 데이터를 삭제할까요?')) return;
  store.resetAll();
  void router.replace('/login');
}
</script>

<template>
  <TopBar title="설정" />
  <div class="screen">
    <p class="section-title">계정</p>
    <div class="card">
      <label class="field" style="margin-bottom: 0">
        <span>보호자 이름</span>
        <input
          :value="store.settings.profileName ?? ''"
          type="text"
          placeholder="보호자"
          @input="store.updateSettings({ profileName: ($event.target as HTMLInputElement).value })"
        />
      </label>
    </div>

    <p class="section-title">메일 계정</p>
    <div class="card">
      <div v-if="mail.account.value" class="row between">
        <div class="grow">
          <strong class="small">{{ mail.provider.label }} 연결됨</strong>
          <p class="muted small" style="margin: 4px 0 0">{{ mail.account.value.email }} · 읽기 전용</p>
        </div>
        <button class="btn" @click="mail.disconnect">연결 해제</button>
      </div>
      <div v-else class="row between">
        <span class="small">{{ mail.provider.label }} 연결 안 됨</span>
        <button class="btn" :disabled="!mail.configured.value || mail.connecting.value" @click="mail.connect()">
          {{ mail.connecting.value ? '연결 중…' : '연결' }}
        </button>
      </div>
      <p v-if="mail.error.value" class="small" style="color: var(--danger)">{{ mail.error.value }}</p>

      <label class="field" style="margin: 14px 0 0">
        <span>구글 OAuth 클라이언트 ID</span>
        <input v-model="clientId" type="text" placeholder="000000-xxxx.apps.googleusercontent.com" />
      </label>
      <button class="btn block" style="margin-top: 8px" @click="saveClientId">
        {{ clientIdSaved ? '저장됨' : '클라이언트 ID 저장' }}
      </button>
      <p class="muted small" style="margin: 10px 0 0">
        Google Cloud 콘솔에서 <strong>웹 애플리케이션</strong> OAuth 클라이언트를 만들고, 승인된 자바스크립트 원본에 이 앱 주소를
        넣은 뒤 클라이언트 ID를 붙여넣으세요. 클라이언트 ID는 비밀값이 아니며 기기에만 저장됩니다. Gmail 읽기 권한만 요청하고,
        메일 본문은 기기 안에서만 처리됩니다.
      </p>
    </div>

    <p class="section-title">알림</p>
    <div class="card">
      <span class="small muted">기본 알림 시점</span>
      <div class="chip-row" style="margin-top: 8px">
        <button
          v-for="offset in OFFSET_CHOICES"
          :key="offset"
          class="chip"
          :class="{ on: store.settings.defaultOffsets.includes(offset) }"
          @click="toggleOffset(offset)"
        >
          {{ offsetLabel(offset) }}
        </button>
      </div>

      <div class="toggle" style="margin-top: 12px">
        <span class="small">하루 전 알림에 준비물 첨부</span>
        <input
          :checked="store.settings.preparationReminder"
          type="checkbox"
          @change="store.updateSettings({ preparationReminder: ($event.target as HTMLInputElement).checked })"
        />
      </div>

      <div class="grid2" style="margin-top: 12px">
        <label class="field" style="margin-bottom: 0">
          <span>재알림 간격(분)</span>
          <input
            :value="store.settings.snoozeMinutes"
            type="number"
            min="1"
            max="180"
            @input="store.updateSettings({ snoozeMinutes: Math.max(1, Number(($event.target as HTMLInputElement).value) || 1) })"
          />
        </label>
        <label class="field" style="margin-bottom: 0">
          <span>재알림 최대 횟수</span>
          <input
            :value="store.settings.maxSnooze"
            type="number"
            min="0"
            max="10"
            @input="store.updateSettings({ maxSnooze: Math.max(0, Number(($event.target as HTMLInputElement).value) || 0) })"
          />
        </label>
      </div>

      <div class="row between" style="margin-top: 14px">
        <span class="small muted">
          기기 알림 권한: {{ permission === 'granted' ? '허용됨' : permission === 'denied' ? '거부됨' : '미설정' }}
        </span>
        <button v-if="permission !== 'granted'" class="btn" @click="ensurePermission().then((p) => (permission = p))">
          요청
        </button>
      </div>
    </div>

    <p class="section-title">기관 관리</p>
    <div class="card">
      <div class="chip-row">
        <button
          v-for="kind in institutions"
          :key="kind"
          class="chip"
          :class="{ on: store.settings.institutionFilter.includes(kind) }"
          @click="store.toggleInstitution(kind)"
        >
          {{ INSTITUTION_LABEL[kind] }}
        </button>
      </div>
      <p class="muted small" style="margin: 10px 0 0">홈·달력에서 보여줄 기관을 선택합니다.</p>
    </div>

    <p class="section-title">날씨</p>
    <div class="card">
      <div class="toggle">
        <span class="small">일정에 날씨 표시</span>
        <input
          :checked="store.settings.weatherEnabled"
          type="checkbox"
          @change="store.updateSettings({ weatherEnabled: ($event.target as HTMLInputElement).checked })"
        />
      </div>

      <p class="small" style="margin: 12px 0 6px">
        현재 지역: <strong>{{ store.settings.region.name }}</strong>
      </p>
      <div class="row">
        <input v-model="query" type="text" class="grow" placeholder="지역 검색 (예: 청주)" @keydown.enter="search" />
        <button class="btn" :disabled="searching || !store.online" @click="search">{{ searching ? '검색 중' : '검색' }}</button>
      </div>
      <p v-if="searchError" class="small" style="color: var(--danger)">{{ searchError }}</p>
      <div v-if="results.length > 0" class="chip-row" style="margin-top: 10px">
        <button v-for="region in results" :key="`${region.latitude},${region.longitude}`" class="chip" @click="pickRegion(region)">
          {{ region.name }}
        </button>
      </div>
      <div class="chip-row" style="margin-top: 10px">
        <button
          v-for="region in PRESET_REGIONS"
          :key="region.name"
          class="chip"
          :class="{ on: store.settings.region.name === region.name }"
          @click="pickRegion(region)"
        >
          {{ region.name }}
        </button>
      </div>
      <button class="btn block" style="margin-top: 12px" :disabled="!store.online" @click="store.refreshWeather(true)">
        예보 새로고침
      </button>
      <p class="muted small" style="margin: 10px 0 0">
        {{
          store.weather ? `마지막 갱신: ${new Date(store.weather.cachedAt).toLocaleString('ko-KR')}` : '아직 예보를 받지 못했습니다.'
        }}
      </p>
    </div>

    <p class="section-title">동기화 · 데이터</p>
    <div class="card">
      <div class="row between">
        <span class="small">연결 상태</span>
        <span class="badge" :class="store.online ? 'ok' : 'warn'">{{ store.online ? '온라인' : '오프라인' }}</span>
      </div>
      <div class="row between" style="margin-top: 8px">
        <span class="small">동기화 대기</span>
        <span class="badge">{{ store.pendingSync }}건</span>
      </div>
      <div class="row between" style="margin-top: 8px">
        <span class="small">마지막 동기화</span>
        <span class="badge">{{ store.lastSyncedAt ? new Date(store.lastSyncedAt).toLocaleString('ko-KR') : '없음' }}</span>
      </div>
      <p class="muted small" style="margin-top: 10px">
        일정·계획표·날씨는 기기에 저장되어 오프라인에서도 조회됩니다. 온라인이 되면 마지막 저장 우선으로 병합합니다.
      </p>
      <div class="row" style="gap: 8px">
        <button class="btn grow" @click="router.push('/widget')">위젯 미리보기</button>
        <button class="btn grow" @click="loadSample">샘플 불러오기</button>
      </div>
      <button class="btn danger block" style="margin-top: 8px" @click="reset">전체 초기화</button>
    </div>
  </div>
</template>

// src/screens/SettingsScreen.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { TopBar } from '../components/TopBar';
import { useApp } from '../store/AppStore';
import { INSTITUTION_LABEL } from '../types';
import type { InstitutionKind, Region } from '../types';
import { offsetLabel } from '../lib/date';
import { OFFSET_CHOICES, ensurePermission } from '../lib/notifications';
import { PRESET_REGIONS, searchRegion } from '../lib/weather';
import { useMailAccount } from '../store/useMailAccount';
import { getGoogleClientId, setGoogleClientId } from '../lib/mail/gmail';

const INSTITUTIONS: InstitutionKind[] = ['kindergarten', 'daycare', 'home'];

export function SettingsScreen() {
  const navigate = useNavigate();
  const { settings, updateSettings, toggleInstitution, refreshWeather, loadSampleData, resetAll, online, pendingSync, lastSyncedAt, weather } =
    useApp();
  const [permission, setPermission] = useState(typeof Notification === 'undefined' ? 'denied' : Notification.permission);
  const [query, setQuery] = useState('');
  const [results, setResults] = useState<Region[]>([]);
  const [searching, setSearching] = useState(false);
  const [searchError, setSearchError] = useState('');
  const mail = useMailAccount();
  const [clientId, setClientId] = useState(() => getGoogleClientId());
  const [clientIdSaved, setClientIdSaved] = useState(false);

  const saveClientId = () => {
    setGoogleClientId(clientId);
    setClientIdSaved(true);
    mail.refresh();
    window.setTimeout(() => setClientIdSaved(false), 2000);
  };

  const pickRegion = (region: Region) => {
    updateSettings({ region });
    setResults([]);
    setQuery('');
    void refreshWeather(true);
  };

  const search = async () => {
    if (!query.trim()) return;
    setSearching(true);
    setSearchError('');
    try {
      setResults(await searchRegion(query.trim()));
    } catch {
      setSearchError('지역을 검색하지 못했습니다. 오프라인이면 아래 목록에서 골라 주세요.');
    } finally {
      setSearching(false);
    }
  };

  return (
    <>
      <TopBar title="설정" />
      <div className="screen">
        <p className="section-title">계정</p>
        <div className="card">
          <label className="field" style={{ marginBottom: 0 }}>
            <span>보호자 이름</span>
            <input
              type="text"
              value={settings.profileName ?? ''}
              onChange={(e) => updateSettings({ profileName: e.target.value })}
              placeholder="보호자"
            />
          </label>
        </div>

        <p className="section-title">메일 계정</p>
        <div className="card">
          {mail.account ? (
            <div className="row between">
              <div className="grow">
                <strong className="small">{mail.provider.label} 연결됨</strong>
                <p className="muted small" style={{ margin: '4px 0 0' }}>
                  {mail.account.email} · 읽기 전용
                </p>
              </div>
              <button className="btn" onClick={mail.disconnect}>
                연결 해제
              </button>
            </div>
          ) : (
            <div className="row between">
              <span className="small">{mail.provider.label} 연결 안 됨</span>
              <button className="btn" onClick={() => void mail.connect()} disabled={!mail.configured || mail.connecting}>
                {mail.connecting ? '연결 중…' : '연결'}
              </button>
            </div>
          )}
          {mail.error && (
            <p className="small" style={{ color: 'var(--danger)' }}>
              {mail.error}
            </p>
          )}

          <label className="field" style={{ marginTop: 14, marginBottom: 0 }}>
            <span>구글 OAuth 클라이언트 ID</span>
            <input
              type="text"
              value={clientId}
              onChange={(e) => setClientId(e.target.value)}
              placeholder="000000-xxxx.apps.googleusercontent.com"
            />
          </label>
          <button className="btn block" style={{ marginTop: 8 }} onClick={saveClientId}>
            {clientIdSaved ? '저장됨' : '클라이언트 ID 저장'}
          </button>
          <p className="muted small" style={{ marginBottom: 0, marginTop: 10 }}>
            Google Cloud 콘솔에서 <strong>웹 애플리케이션</strong> OAuth 클라이언트를 만들고, 승인된 자바스크립트 원본에
            이 앱 주소를 넣은 뒤 클라이언트 ID를 붙여넣으세요. 클라이언트 ID는 비밀값이 아니며 기기에만 저장됩니다.
            Gmail 읽기 권한만 요청하고, 메일 본문은 기기 안에서만 처리됩니다.
          </p>
        </div>

        <p className="section-title">알림</p>
        <div className="card">
          <span className="small muted">기본 알림 시점</span>
          <div className="chip-row" style={{ marginTop: 8 }}>
            {OFFSET_CHOICES.map((offset) => (
              <button
                key={offset}
                className={`chip ${settings.defaultOffsets.includes(offset) ? 'on' : ''}`}
                onClick={() =>
                  updateSettings({
                    defaultOffsets: settings.defaultOffsets.includes(offset)
                      ? settings.defaultOffsets.filter((o) => o !== offset)
                      : [...settings.defaultOffsets, offset],
                  })
                }
              >
                {offsetLabel(offset)}
              </button>
            ))}
          </div>

          <div className="toggle" style={{ marginTop: 12 }}>
            <span className="small">하루 전 알림에 준비물 첨부</span>
            <input
              type="checkbox"
              checked={settings.preparationReminder}
              onChange={(e) => updateSettings({ preparationReminder: e.target.checked })}
            />
          </div>

          <div className="grid2" style={{ marginTop: 12 }}>
            <label className="field" style={{ marginBottom: 0 }}>
              <span>재알림 간격(분)</span>
              <input
                type="number"
                min={1}
                max={180}
                value={settings.snoozeMinutes}
                onChange={(e) => updateSettings({ snoozeMinutes: Math.max(1, Number(e.target.value) || 1) })}
              />
            </label>
            <label className="field" style={{ marginBottom: 0 }}>
              <span>재알림 최대 횟수</span>
              <input
                type="number"
                min={0}
                max={10}
                value={settings.maxSnooze}
                onChange={(e) => updateSettings({ maxSnooze: Math.max(0, Number(e.target.value) || 0) })}
              />
            </label>
          </div>

          <div className="row between" style={{ marginTop: 14 }}>
            <span className="small muted">
              기기 알림 권한: {permission === 'granted' ? '허용됨' : permission === 'denied' ? '거부됨' : '미설정'}
            </span>
            {permission !== 'granted' && (
              <button
                className="btn"
                onClick={async () => {
                  setPermission(await ensurePermission());
                }}
              >
                요청
              </button>
            )}
          </div>
        </div>

        <p className="section-title">기관 관리</p>
        <div className="card">
          <div className="chip-row">
            {INSTITUTIONS.map((kind) => (
              <button
                key={kind}
                className={`chip ${settings.institutionFilter.includes(kind) ? 'on' : ''}`}
                onClick={() => toggleInstitution(kind)}
              >
                {INSTITUTION_LABEL[kind]}
              </button>
            ))}
          </div>
          <p className="muted small" style={{ marginBottom: 0, marginTop: 10 }}>
            홈·달력에서 보여줄 기관을 선택합니다.
          </p>
        </div>

        <p className="section-title">날씨</p>
        <div className="card">
          <div className="toggle">
            <span className="small">일정에 날씨 표시</span>
            <input type="checkbox" checked={settings.weatherEnabled} onChange={(e) => updateSettings({ weatherEnabled: e.target.checked })} />
          </div>

          <p className="small" style={{ marginTop: 12, marginBottom: 6 }}>
            현재 지역: <strong>{settings.region.name}</strong>
          </p>
          <div className="row">
            <input
              type="text"
              className="grow"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') void search();
              }}
              placeholder="지역 검색 (예: 청주)"
            />
            <button className="btn" onClick={() => void search()} disabled={searching || !online}>
              {searching ? '검색 중' : '검색'}
            </button>
          </div>
          {searchError && (
            <p className="small" style={{ color: 'var(--danger)' }}>
              {searchError}
            </p>
          )}
          {results.length > 0 && (
            <div className="chip-row" style={{ marginTop: 10 }}>
              {results.map((region) => (
                <button key={`${region.latitude},${region.longitude}`} className="chip" onClick={() => pickRegion(region)}>
                  {region.name}
                </button>
              ))}
            </div>
          )}
          <div className="chip-row" style={{ marginTop: 10 }}>
            {PRESET_REGIONS.map((region) => (
              <button
                key={region.name}
                className={`chip ${settings.region.name === region.name ? 'on' : ''}`}
                onClick={() => pickRegion(region)}
              >
                {region.name}
              </button>
            ))}
          </div>
          <button className="btn block" style={{ marginTop: 12 }} onClick={() => void refreshWeather(true)} disabled={!online}>
            예보 새로고침
          </button>
          <p className="muted small" style={{ marginBottom: 0, marginTop: 10 }}>
            {weather ? `마지막 갱신: ${new Date(weather.cachedAt).toLocaleString('ko-KR')}` : '아직 예보를 받지 못했습니다.'}
          </p>
        </div>

        <p className="section-title">동기화 · 데이터</p>
        <div className="card">
          <div className="row between">
            <span className="small">연결 상태</span>
            <span className={`badge ${online ? 'ok' : 'warn'}`}>{online ? '온라인' : '오프라인'}</span>
          </div>
          <div className="row between" style={{ marginTop: 8 }}>
            <span className="small">동기화 대기</span>
            <span className="badge">{pendingSync}건</span>
          </div>
          <div className="row between" style={{ marginTop: 8 }}>
            <span className="small">마지막 동기화</span>
            <span className="badge">{lastSyncedAt ? new Date(lastSyncedAt).toLocaleString('ko-KR') : '없음'}</span>
          </div>
          <p className="muted small" style={{ marginTop: 10 }}>
            일정·계획표·날씨는 기기에 저장되어 오프라인에서도 조회됩니다. 온라인이 되면 마지막 저장 우선으로 병합합니다.
          </p>
          <div className="row" style={{ gap: 8 }}>
            <button className="btn grow" onClick={() => navigate('/widget')}>
              위젯 미리보기
            </button>
            <button
              className="btn grow"
              onClick={() => {
                if (window.confirm('샘플 일정과 계획표 메일로 덮어쓸까요?')) loadSampleData();
              }}
            >
              샘플 불러오기
            </button>
          </div>
          <button
            className="btn danger block"
            style={{ marginTop: 8 }}
            onClick={() => {
              if (window.confirm('저장된 모든 데이터를 삭제할까요?')) {
                resetAll();
                navigate('/login', { replace: true });
              }
            }}
          >
            전체 초기화
          </button>
        </div>
      </div>
    </>
  );
}
