// src/components/TopBar.tsx
import { useNavigate } from 'react-router-dom';
import type { ReactNode } from 'react';

interface Props {
  title: string;
  subtitle?: string;
  back?: boolean;
  actions?: ReactNode;
}

export function TopBar({ title, subtitle, back, actions }: Props) {
  const navigate = useNavigate();
  return (
    <header className="topbar">
      {back && (
        <button className="icon-btn" onClick={() => navigate(-1)} aria-label="뒤로">
          ←
        </button>
      )}
      <div className="grow">
        <h1>{title}</h1>
        {subtitle && <p className="sub">{subtitle}</p>}
      </div>
      {actions}
    </header>
  );
}

// src/components/TopBar.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';

defineProps<{ title: string; subtitle?: string; back?: boolean }>();
const router = useRouter();
</script>

<template>
  <header class="topbar">
    <button v-if="back" class="icon-btn" aria-label="뒤로" @click="router.back()">←</button>
    <div class="grow">
      <h1>{{ title }}</h1>
      <p v-if="subtitle" class="sub">{{ subtitle }}</p>
    </div>
    <slot name="actions" />
  </header>
</template>
